feat/edit delete pieces
alper92/capstone-project pull request #8
Opened 2023-08-18 10:49 UTC by alper92

#7

2023-08-18 12:08 UTC, CJAkkuec requested changes
Looking good, just a few suggestions. 👍

2023-08-18 12:08 UTC, CJAkkuec commented on pages/admin.js
> +    const imageFile = event.target.files[0];
Up to you if you want to move this `event.target` to its own variable as well here. I usually do it, because it makes it more apparent what the event target actually is, but it doesn't really "save" any lines of code, just makes it more easily readable.

2023-08-18 12:31 UTC, alper92 commented
> Looking good, just a few suggestions. 👍

Everything works somehow but in many places I have workaround solutions to achieve what I initially wanted to achieve. And I do not know where to address them. `admin.js` should be the place where I handle all the art pieces (add, delete and update). That was the initial Idea. BUT:  I spend hours trying to pass `editedArtPiece`-Object  from `ArtPiecesListForm` to the handlerFunction in `admin.js`. So then I ended up with passing setter functions to components. If I try now to not pass setter functions I'm pretty sure my whole code will be destroyed.

2023-08-18 12:46 UTC, alper92 commented on pages/admin.js
> +    const imageFile = event.target.files[0];
True, I will think about that! currently everything I need for validation is in `imageFile`. I. E. the name, the size, the format etc.

2023-08-18 13:16 UTC, CJAkkuec commented
> > Looking good, just a few suggestions. 👍
> 
> Everything works somehow but in many places I have workaround solutions to achieve what I initially wanted to achieve. And I do not know where to address them. `admin.js` should be the place where I handle all the art pieces (add, delete and update). That was the initial Idea. BUT: I spend hours trying to pass `editedArtPiece`-Object from `ArtPiecesListForm` to the handlerFunction in `admin.js`. So then I ended up with passing setter functions to components. If I try now to not pass setter functions I'm pretty sure my whole code will be destroyed.

Instead of passing the setter directly, you can pass the handlers. You're using this pattern with pretty much every other setter/etc in `admin.js` as well.

Just define a function like the following in your `_app.js`
```js
function handleArtPieces (artPiecesArray) {
setArtPieces(artPiecesArray)
}
```
and pass `handleArtPieces` to your lower level components, like so:
```js
<Component
        {...pageProps}
        artPieces={artPieces}
        handleArtPieces={handleArtPieces}
      />
```

Then you switch over to your `admin.js` and just cmd + f "setArtPieces" and replace it with "handleArtPieces", and do the same wherever else you used the setter.

Nothing will explode, it's just best practice.

2023-08-18 14:31 UTC, alper92 commented
> > > Looking good, just a few suggestions. 👍
> > 
> > 
> > Everything works somehow but in many places I have workaround solutions to achieve what I initially wanted to achieve. And I do not know where to address them. `admin.js` should be the place where I handle all the art pieces (add, delete and update). That was the initial Idea. BUT: I spend hours trying to pass `editedArtPiece`-Object from `ArtPiecesListForm` to the handlerFunction in `admin.js`. So then I ended up with passing setter functions to components. If I try now to not pass setter functions I'm pretty sure my whole code will be destroyed.
> 
> Instead of passing the setter directly, you can pass the handlers. You're using this pattern with pretty much every other setter/etc in `admin.js` as well.
> 
> Just define a function like the following in your `_app.js`
> 
> ```js
> function handleArtPieces (artPiecesArray) {
> setArtPieces(artPiecesArray)
> }
> ```
> 
> and pass `handleArtPieces` to your lower level components, like so:
> 
> ```js
> <Component
>         {...pageProps}
>         artPieces={artPieces}
>         handleArtPieces={handleArtPieces}
>       />
> ```
> 
> Then you switch over to your `admin.js` and just cmd + f "setArtPieces" and replace it with "handleArtPieces", and do the same wherever else you used the setter.
> 
> Nothing will explode, it's just best practice.

Thank you for your advice! I lifted all states up.

2023-08-21 08:45 UTC, Kheirah approved these changes
Very well done!

I'll approve of your changes because the code works. Have a look at the comments below, though, as I'm pointing out some of discrepancies. See if you can fix them quickly before moving on to QA.

2023-08-21 08:45 UTC, Kheirah commented on pages/admin.js
> +  const allowedFileSize = 600000;
Let's make it a round 600 KB. Since everything is in binary, you have to multiply 1024 bytes (= 1 KB) by some number, like 600, and you get that many bytes back.
```suggestion
  const allowedFileSize = 614400;
```

2023-08-21 08:45 UTC, Kheirah commented on pages/admin.js
> +    } else window.alert(`Your uploaded file is bigger then ${allowedFileSize / 1000}KB.`);
Likewise, you'd have to divide by 1024 here to get tha correct amount of kilobytes.
(Well, actually it's called kibibytes in this case but that's usually what's displayed in Windows, Linux and Mac).

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPieceForm/ArtPieceForm.js
> +import { styled } from "styled-components";
Even though it doesn't scream at you, it's actually a default export.
```suggestion
import styled from "styled-components";
```

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPieceForm/ArtPieceForm.js
> +          Upload your art piece: *Maximum file size is {allowedFileSize / 1000}KB
1024 here as well.

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPieceForm/ArtPieceForm.js
> +            <option defaultValue={artPieceToEdit?.Portrait}>Portraits</option>
You probably want to use `value` instead of `defaultValue` here since `defaultValue` doesn't exist on `option` elements if remember correctly.

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPieceForm/ArtPieceForm.js
> +            <option defaultValue={artPieceToEdit?.Acryl}>Acryl</option>
Same here, `value` for `defaultValue`.

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPieceForm/ArtPieceForm.js
> +            id="widthReal"
Are you sure you are connecting the label to the right input element here? =)
`heightReal` currently connects to the next input because this input's `id` is "widthReal".

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPieceForm/ArtPieceForm.js
> +            id="heightReal"
The same applies here.

2023-08-21 08:45 UTC, Kheirah commented on components/AdminEditImagePreview/AdminEditImagePreview.js
> +import { styled } from "styled-components";
```suggestion
import styled from "styled-components";
```

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPiecesList/ArtPiecesListForm.js
> +            id="widthReal"
Check the `label` to `input` connection here, too. The `htmlFor` says something about height but it's actually the width input element.

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPiecesList/ArtPiecesListForm.js
> +            id="heightReal"
Same here.

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPiecesList/AdminArtPiecesList.js
> +                <FontAwesomeIcon icon={faPencil} />
I love FontAwesome!

2023-08-21 08:45 UTC, Kheirah commented on components/AdminArtPiecesList/ArtPiecesListForm.js
> +import { styled } from "styled-components";
```suggestion
import styled from "styled-components";
```

2023-08-21 09:01 UTC, alper92 commented on components/AdminArtPiecesList/ArtPiecesListForm.js
> +            id="widthReal"
THANKS A LOT. Such a silly mistake!

2023-08-21 09:01 UTC, alper92 commented on components/AdminArtPiecesList/AdminArtPiecesList.js
> +                <FontAwesomeIcon icon={faPencil} />
Same here!

2023-08-21 09:04 UTC, alper92 commented
> Very well done!
> 
> I'll approve of your changes because the code works. Have a look at the comments below, though, as I'm pointing out some of discrepancies. See if you can fix them quickly before moving on to QA.

Thank you very very much!!!

2023-08-21 09:04 UTC, merged